name: Build documentation
on:
  push:
    branches:
    - stable
    - latest
  create:
    tags:
    - '*'
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
    # Prepare the workspace
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Make api documentation
    - name: Install dependencies (api)
      run: make install
      working-directory: api
    - name: Generate doc (api)
      run: make doc
      working-directory: api
    - name: Upload api doc
      uses: actions/upload-artifact@v2
      with:
        name: api-doc
        path: api/api-doc
    # Make documentation
    - name: Install dependencies (docs)
      run: make image
      working-directory: docs
    - name: Generate doc (docs)
      run: make doc
      working-directory: docs
    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/build
    # Make version folder
    - name: Clone GitHub page repository
      uses: actions/checkout@v2
      with:
        repository: "Fastwf/Fastwf.github.io"
        path: .github-page
        token: ${{ secrets.SITE_GITHUB_TOKEN }}
    - name: Update GitHub page repository
      run: |
        mkdir -p ".github-page/${GITHUB_REF##*/}"
        cp -R -t ".github-page/${GITHUB_REF##*/}" docs/build/*
        cp -R -t ".github-page/${GITHUB_REF##*/}" api/api-doc
        echo '{"version":"'${GITHUB_REF##*/}'"}' > ".github-page/${GITHUB_REF##*/}/version.json"
        python make_version.py ".github-page/" ".github-page/versions.json"
    - name: Commit changes
      run: |
        git config user.name "GitHub action"
        git config user.email "github-actions@github.com"
        if [ $(git status --porcelain | wc -l) -ne 0 ]
        then
          git add .
          git commit -m "Update the documentation for '${GITHUB_REF##*/}'"
          git push
        fi
      working-directory: .github-page
